#!/usr/bin/env bash
# script that installs Nginx

# check if nginx is installeed
# install it if not

sudo apt-get -y update
sudo apt-get install -y nginx

# ensure nginx is listening to port 80
ufw allow 'Nginx HTTP'

# set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx without systemctl
sudo service nginx restart
