#!/usr/bin/env bash

server {
        listen 80;
        server_name 127.0.0.1 100.26.53.35;

        location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Served-By "505046-web-01";
        }
}
